"use client";
import {useEffect,useState} from "react";
import {londonStartOfDay} from "@/lib/cancellationPolicy";
import styles from "./RentalRequestApply.module.css";
const DAY=86400000,iso=(at:number)=>new Date(at).toISOString().slice(0,10);
export function RentalRequestCalendar({initial,start,end,onStart,onEnd,disabled,request=false}:{initial:number;start:string;end:string;onStart:(value:string)=>void;onEnd:(value:string)=>void;disabled:boolean;request?:boolean}){
 const [month,setMonth]=useState(()=>{const d=new Date(start||initial);return Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1);}),[field,setField]=useState<"start"|"end">("start");
 useEffect(()=>{const selected=field==="start"?start:end;if(!selected)return;const d=new Date(selected+"T00:00:00Z");setMonth(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1));},[start,end,field]);
 const d=new Date(month),year=d.getUTCFullYear(),index=d.getUTCMonth(),count=new Date(Date.UTC(year,index+1,0)).getUTCDate(),offset=(d.getUTCDay()+6)%7;
 const minimum=londonStartOfDay(Date.now()),from=start?Date.parse(start+"T00:00:00Z"):undefined,to=end?Date.parse(end+"T00:00:00Z"):undefined;
 return <div className={styles.calendar} aria-label={request?"Choose requested rental dates":"Choose agreed rental dates"}><div className={styles.calendarFields}><button type="button" aria-pressed={field==="start"} onClick={()=>setField("start")} disabled={disabled}>Collection</button><button type="button" aria-pressed={field==="end"} onClick={()=>setField("end")} disabled={disabled}>Return</button></div><header><button type="button" aria-label="Previous month" disabled={disabled} onClick={()=>setMonth(Date.UTC(year,index-1,1))}>‹</button><strong>{d.toLocaleDateString("en-GB",{timeZone:"UTC",month:"long",year:"numeric"})}</strong><button type="button" aria-label="Next month" disabled={disabled} onClick={()=>setMonth(Date.UTC(year,index+1,1))}>›</button></header><div className={styles.calendarGrid}>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><span key={day}>{day}</span>)}{Array.from({length:offset},(_,i)=><span key={`empty-${i}`} aria-hidden="true"/>)}{Array.from({length:count},(_,i)=>{const at=Date.UTC(year,index,i+1),value=iso(at),selected=value===start||value===end;return <button type="button" key={value} aria-label={`${field==="start"?"Collection":"Return"} ${new Date(at).toLocaleDateString("en-GB",{timeZone:"UTC",weekday:"long",day:"numeric",month:"long",year:"numeric"})}`} aria-pressed={selected} data-range={from!==undefined&&to!==undefined&&at>=from&&at<=to} disabled={disabled||at<minimum||(field==="end"&&from!==undefined&&at<from)} onClick={()=>{if(field==="start"){onStart(value);if(end&&end<value)onEnd("");setField("end");}else onEnd(value);}}>{i+1}</button>;})}</div><p className={styles.note}>Selecting {field==="start"?"collection":"return"} date · {request?"availability will be checked by the team.":"availability checked for the complete period."}</p></div>;
}
