import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
export default function ReferralTerms(){const sections=[
 ["A first rental for your friend","Every authenticated account has a personal code. A different customer with a verified account may enter it at checkout for £10 off their first website rental, capped at the rental charge. Prior paid rentals, including later cancelled paid bookings, are not first rentals. Unpaid abandoned checkouts must be cancelled before claiming the offer. Codes have no cash value and cannot be sold."],
 ["One reward for you","After a referred friend’s paid rental is verified, collected, completed and returned with its return statement recorded, the referrer receives one 40% rental voucher. No reward is issued for pending, cancelled, unpaid or incomplete rentals. Self-referrals and shared payment methods do not qualify for a referrer reward. The reward is once per referrer account for the lifetime of the account, not once per friend. Further referrals may still help friends but do not generate more rewards."],
 ["Use and expiry","The 40% voucher covers rental charges only. It is automatically selected at the next eligible checkout when it produces the best single saving, and consumed only after successful payment. It expires three calendar months after issue (a month-end date is capped to the last day of the expiry month). A checkout reserved before expiry may complete within its normal payment window. Unpaid cancellation releases the reservation, subject to the original expiry. Paid cancellation, refund, account reactivation or rejoining does not reset use, extend expiry or regenerate the voucher."],
 ["No stacking and normal security","Only one price benefit applies: referral, promo, item offer, Encore, membership weekend or delivery saving, or earned store credit. The once-only £5 Starter / £10 Pro or Studio joining credit is the sole stacking exception, capped at remaining rental charges. Multiple earned credit grants count as one credit benefit. Refund credits may pay the remaining eligible rental/delivery balance. Referral offers always require normal upfront refundable security, the applicable card hold and required verification, including for paid members and returning renters. Security, holds, delivery, subscription fees, damage, late fees and Film Fund fees are outside the referral rental discount."],
 ["Fair use and communication","Use genuine separate customer accounts. We may withhold a reward for self-referral, shared payment identity or fraudulent activity and explain this when queried. An account’s referral panel shows its code and reward status without revealing a friend’s private rental details. Promotional referral announcements go only to opted-in verified account holders and include unsubscribe. Opting into marketing does not grant a rental discount. Existing agreed rentals retain their confirmed prices and statutory rights are unaffected."],
 ];return <><SiteHeader/><main className="mx-auto max-w-3xl px-6 py-16"><Link href="/account" className="text-sm text-accent-300">← Your account</Link><h1 className="mt-6 font-display text-4xl text-white">Pass the camera on.</h1><p className="mt-3 text-xs text-white/40">Referral terms · 2026-10-referrals-v2 · effective on acceptance</p><div className="mt-10 space-y-8">{sections.map(([h,p])=><section key={h}><h2 className="text-lg text-white">{h}</h2><p className="mt-2 text-sm leading-7 text-white/60">{p}</p></section>)}</div></main></>;}
