"use node";
import {rentalEmail,emailRows} from "../shared/rentalEmail";
import { returnStatementEmail } from "../shared/returnStatement";
import { rentalBillingLines } from "./lib/rentalBillingLines";

import { internalAction } from "./_generated/server";
import { api, internal } from "./_generated/api";
import { v } from "convex/values";
import { sendMail } from "./lib/mailer";

const amount = (value: number) => `£${value.toFixed(2)}`;
const esc = (value: string) => value.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);

/** The customer attachment must contain an actual bounded PDF, never a route error or JSON. */
async function fetchInvoicePdf(url:string,secret:string):Promise<Buffer>{
 const response=await fetch(url,{headers:{"x-invoice-key":secret},signal:AbortSignal.timeout(20_000)});
 if(!response.ok||response.headers.get("content-type")?.split(";")[0].trim().toLowerCase()!=="application/pdf")throw Error("Invoice route did not return a PDF");
 const bytes=Buffer.from(await response.arrayBuffer());
 if(bytes.length<5||bytes.length>10_000_000||bytes.subarray(0,5).toString("ascii")!=="%PDF-")throw Error("Invoice PDF is invalid");
 return bytes;
}

/** Emails the renter a receipt with the PDF invoice attached. The PDF is generated by the
 *  Next.js route (Node/react-pdf on Vercel) and fetched here with the server INVOICE_SECRET.
 *  Sends through the shared transport, so it follows whichever of Gmail/Resend is
 *  configured. Sends without the attachment if the PDF route is unreachable, so the
 *  receipt still goes out. */
export const invoiceEmail = internalAction({
  args: { prepareOnly:v.optional(v.boolean()),deliveryKey:v.optional(v.string()), bookingId: v.id("bookings") },
  handler: async (ctx, { prepareOnly, deliveryKey, bookingId }) => {
    const b: any = await ctx.runQuery(internal.bookings.receiptContext, { bookingId });
    if (!b || !b.guestEmail) return null;

    const app = process.env.APP_URL ?? "https://dbcinemarentals.com";
    const secret = process.env.INVOICE_SECRET;

    let attachment: { filename: string; content: string } | null = null;
    if (secret) {
      try {
        const buf=await fetchInvoicePdf(`${app}/api/invoice/${bookingId}`,secret);
        attachment={filename:`DbCinema-receipt-${String(bookingId).slice(-8)}.pdf`,content:buf.toString("base64")};
      } catch {
        /* fall through — send without attachment */
      }
    }

    const rows:Array<[string,string]>=rentalBillingLines(b).map((li:any)=>[li.title,amount(li.lineTotal)]);
    rows.push(["Rental subtotal",amount(b.subtotal)]);
    if(b.discount>0)rows.push(["Discount",`−${amount(b.discount)}`]);
    if(b.creditApplied>0)rows.push(["Account credit applied",`−${amount(b.creditApplied)}`]);
    if(b.deliveryFee>0)rows.push(["Delivery",amount(b.deliveryFee)]);
    rows.push(["Refundable deposit paid",amount(b.depositAmount)],["Total paid",amount(b.total)]);
    const url=`${app}/account?rental=${encodeURIComponent(bookingId)}#chat`;
    const payload={
      deliveryKey,
      to:b.guestEmail,
      subject:"Your DB Cinema rental receipt",
      html:rentalEmail({title:"Your payment receipt",preview:`Payment received: ${amount(b.total)}. Your rental receipt is ready.`,url,button:"View rental and receipt",body:`<p>Your receipt${attachment?" is attached as a PDF":" is below. You can also download it from your account"}.</p>${emailRows(rows)}${b.membershipCreditApplied?`<p>Account credit above includes ${amount(b.membershipCreditApplied)} from your first subscription month. Subscription charges are itemised separately by Stripe.</p>`:""}<p>Any card authorisation is separate from the payment total shown above.</p><p style="font-size:12px">No VAT was charged. This is a payment receipt, not a VAT invoice.</p>`}),
      attachments:attachment?[attachment]:[],
    };
    return prepareOnly?payload:sendMail(payload);
  },
});

/** Immutable return settlement: send the PDF only after the refund/capture and
 * late-fee assessment have been recorded. A failed PDF/email is retried hourly. */
export const returnSettlementEmail = internalAction({
  args: { bookingId: v.id("bookings") },
  handler: async (ctx, { bookingId }) => {
    if (!(await ctx.runMutation(internal.bookings.claimReturnStatementEmail, { bookingId }))) return;
    const context: any = await ctx.runQuery(internal.bookings.returnStatementContext, { bookingId });
    const s = context?.statement;
    const secret = process.env.INVOICE_SECRET;
    const app = process.env.APP_URL ?? "https://dbcinemarentals.com";
    if (!s?.customerEmail || !secret) {
      await ctx.runMutation(internal.bookings.markReturnStatementEmail, { bookingId, sent: false });
      return;
    }
    let sent = false;
    try {
      const pdf=await fetchInvoicePdf(`${app}/api/invoice/${bookingId}?phase=return`,secret);
      const content = returnStatementEmail(s,false,`${app}/account?rental=${encodeURIComponent(bookingId)}#chat`);
      sent = await sendMail({
        ...content,
        attachments: [{ filename: `DbCinema-return-${String(bookingId).slice(-8)}.pdf`, content: pdf.toString("base64") }],
      });
    } catch (error) { console.error("Return statement email failed", bookingId, error); }
    await ctx.runMutation(internal.bookings.markReturnStatementEmail, { bookingId, sent });
  },
});

export const retryReturnStatements = internalAction({
  args: {},
  handler: async (ctx) => {
    const ids: any[] = await ctx.runQuery(internal.bookings.dueReturnStatementEmails, {});
    for (const bookingId of ids) await ctx.runAction(internal.invoice.returnSettlementEmail, { bookingId });
  },
});
