"use node";

import { internalAction } from "./_generated/server";
import { api, internal } from "./_generated/api";
import { v } from "convex/values";
import { sendMail } from "./lib/mailer";

const amount = (value: number) => `£${value.toFixed(2)}`;
const esc = (value: string) => value.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);

/** Emails the renter a receipt with the PDF invoice attached. The PDF is generated by the
 *  Next.js route (Node/react-pdf on Vercel) and fetched here with the server INVOICE_SECRET.
 *  Sends through the shared transport, so it follows whichever of Gmail/Resend is
 *  configured. Sends without the attachment if the PDF route is unreachable, so the
 *  receipt still goes out. */
export const invoiceEmail = internalAction({
  args: { bookingId: v.id("bookings") },
  handler: async (ctx, { bookingId }) => {
    const b: any = await ctx.runQuery(api.bookings.get, { bookingId });
    if (!b || !b.guestEmail) return;

    const app = process.env.APP_URL ?? "https://dbcinemarentals.com";
    const secret = process.env.INVOICE_SECRET;

    let attachment: { filename: string; content: string } | null = null;
    if (secret) {
      try {
        const res = await fetch(`${app}/api/invoice/${bookingId}`, { headers: { "x-invoice-key": secret } });
        if (res.ok) {
          const buf = Buffer.from(await res.arrayBuffer());
          attachment = {
            filename: `DbCinema-receipt-${String(bookingId).slice(-8)}.pdf`,
            content: buf.toString("base64"),
          };
        }
      } catch {
        /* fall through — send without attachment */
      }
    }

    const items = b.lineItems.map((li: any) => `• ${esc(li.title)} — ${amount(li.lineTotal)}`).join("<br>");
    await sendMail({
      to: b.guestEmail,
      subject: "Your Db Cinema receipt 🎬",
      html: `<h2>Receipt</h2><p>Thanks for renting with Db Cinema. Your receipt${attachment ? " is attached as a PDF" : " is below"}.</p><p>${items}</p><p>Total paid: <b>${amount(b.total)}</b> (including ${amount(b.depositAmount)} refundable security payment). A separate card hold is an authorisation, not a payment.</p><p>Db Cinema Rentals is not VAT registered. No VAT was charged; this is not a VAT invoice.</p>`,
      attachments: attachment ? [attachment] : undefined,
    });
  },
});

/** Immutable return settlement: send the PDF only after the refund/capture and
 * late-fee assessment have been recorded. A failed PDF/email is retried hourly. */
export const returnSettlementEmail = internalAction({
  args: { bookingId: v.id("bookings") },
  handler: async (ctx, { bookingId }) => {
    if (!(await ctx.runMutation(internal.bookings.claimReturnStatementEmail, { bookingId }))) return;
    const context: any = await ctx.runQuery(internal.bookings.returnStatementContext, { bookingId });
    const s = context?.statement;
    const secret = process.env.INVOICE_SECRET;
    const app = process.env.APP_URL ?? "https://dbcinemarentals.com";
    if (!s?.customerEmail || !secret) {
      await ctx.runMutation(internal.bookings.markReturnStatementEmail, { bookingId, sent: false });
      return;
    }
    let sent = false;
    try {
      const res = await fetch(`${app}/api/invoice/${bookingId}?phase=return`, { headers: { "x-invoice-key": secret } });
      if (!res.ok) throw new Error(`Return PDF responded ${res.status}`);
      const pdf = Buffer.from(await res.arrayBuffer());
      if (!pdf.length || pdf.length > 10_000_000) throw new Error("Return PDF size is invalid");
      const lines = s.lineItems.map((line: any) => `<li>${esc(line.title)} × ${line.qty}: ${amount(line.lineTotal)}</li>`).join("");
      const late = s.lateAssessed > 0
        ? `<p><b>Separate late rental time assessed: ${amount(s.lateAssessed)}.</b> This is not yet collected. An itemised notice and seven-day dispute period follow separately.</p>`
        : s.lateWaived > 0 ? `<p>Late rental time of ${amount(s.lateWaived)} was waived.</p>` : "";
      sent = await sendMail({
        to: s.customerEmail,
        subject: `Db Cinema return statement ${s.number}`,
        html: `<h2>Your rental return statement</h2><p>Your itemised PDF return statement is attached. Db Cinema Rentals is not VAT registered, so this is not a VAT invoice.</p><ul>${lines}</ul><p>Rental subtotal ${amount(s.subtotal)}; discount −${amount(s.discount)}; delivery ${amount(s.deliveryFee)}; store credit used −${amount(s.creditApplied)}.</p><p>Confirmed rental payment refunds ${amount(s.rentalRefunded??0)}. Refundable security payment paid ${amount(s.securityPaid)}; refunded ${amount(s.securityRefunded)}. Documented damage/loss retained ${amount(s.damageTotal)}, including ${amount(s.damageFromHold)} from the authorised hold.</p>${late}<p>If any return detail is wrong, reply to this email.</p>`,
        attachments: [{ filename: `DbCinema-return-${String(bookingId).slice(-8)}.pdf`, content: pdf.toString("base64") }],
      });
    } catch (error) { console.error("Return statement email failed", bookingId, error); }
    await ctx.runMutation(internal.bookings.markReturnStatementEmail, { bookingId, sent });
  },
});

export const retryReturnStatements = internalAction({
  args: {},
  handler: async (ctx) => {
    const ids: any[] = await ctx.runQuery(internal.bookings.dueReturnStatementEmails, {});
    for (const bookingId of ids) await ctx.runAction(internal.invoice.returnSettlementEmail, { bookingId });
  },
});
