"use node";

import { internalAction } from "./_generated/server";
import { api } from "./_generated/api";
import { v } from "convex/values";

/** Emails the renter a receipt with the PDF invoice attached. The PDF is generated by the
 *  Next.js route (Node/react-pdf on Vercel) and fetched here with the server INVOICE_SECRET.
 *  No-ops silently until RESEND_API_KEY is configured. Sends without the attachment if the
 *  PDF route is unreachable, so the receipt still goes out. */
export const invoiceEmail = internalAction({
  args: { bookingId: v.id("bookings") },
  handler: async (ctx, { bookingId }) => {
    const key = process.env.RESEND_API_KEY;
    if (!key) return;
    const b: any = await ctx.runQuery(api.bookings.get, { bookingId });
    if (!b || !b.guestEmail) return;

    const app = process.env.APP_URL ?? "https://dbcinemarentals.com";
    const secret = process.env.INVOICE_SECRET;

    let attachment: { filename: string; content: string } | null = null;
    if (secret) {
      try {
        const res = await fetch(`${app}/api/invoice/${bookingId}?key=${encodeURIComponent(secret)}`);
        if (res.ok) {
          const buf = Buffer.from(await res.arrayBuffer());
          attachment = {
            filename: `DbCinema-receipt-${String(bookingId).slice(-8)}.pdf`,
            content: buf.toString("base64"),
          };
        }
      } catch {
        /* fall through — send without attachment */
      }
    }

    const from = process.env.RESEND_FROM ?? "Db Cinema <onboarding@resend.dev>";
    const items = b.lineItems.map((li: any) => `• ${li.title} — £${li.lineTotal}`).join("<br>");
    const body: any = {
      from,
      to: b.guestEmail,
      reply_to: process.env.OWNER_EMAIL ?? "dbcinemaproductions@gmail.com",
      subject: "Your Db Cinema receipt 🎬",
      html: `<h2>Receipt</h2><p>Thanks for renting with Db Cinema. Your receipt${attachment ? " is attached as a PDF" : " is below"}.</p><p>${items}</p><p>Total paid: <b>£${b.total}</b> (incl. £${b.depositAmount} refundable deposit)</p>`,
    };
    if (attachment) body.attachments = [attachment];

    try {
      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: { authorization: `Bearer ${key}`, "content-type": "application/json" },
        body: JSON.stringify(body),
      });
    } catch {
      /* best-effort */
    }
  },
});
