import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { MEMBERSHIP_TERMS_VERSION } from "@/lib/membership";
export default function MembershipTerms() {
 const sections = [
  ["Your membership", "DB Cinema Rentals offers Starter at £19, Pro at £49 and Studio at £99 per month, billed in GBP. You must be at least 18 and have an account. These are recurring memberships, not a single rental purchase. We are not VAT registered and do not add VAT."],
  ["Welcome offer and renewal", "New members may choose seven free days followed by the selected monthly fee, or start a paid monthly membership immediately. The former £20 welcome-credit offer is no longer available for new checkouts; previously granted credits and already accepted offers retain their applicable terms. The free-week offer is available once per customer and cannot be repeated by canceling and rejoining. Stripe shows your first charge and renewal before you approve. The free week earns no monthly credit and does not waive the upfront rental security payment."],
  ["Monthly credit", "Each successfully paid monthly membership fee earns rental store credit equal to the amount actually paid plus the plan bonus: Starter 10% (110% total), Pro 20% (120% total), Studio 30% (130% total). Rental charges, security payments, taxes, free invoices and proration adjustments do not earn this credit. When you add a paid membership to a rental in the same checkout, only first-month credit and the qualifying joining offer apply to that booking. The upfront refundable security payment, full card hold and verification remain required; weekend deals, delivery benefits and the security waiver begin after that booking is confirmed and apply to future bookings. The first month’s credit is applied immediately to the eligible rental charge after existing account credits, up to the remaining rental cost. The membership fee remains payable in full. This first-month credit cannot cover delivery, membership fees or refundable security, and is conditional on successful payment of that combined checkout. Any unused first-month credit and later monthly credits are available after the paid invoice is confirmed, stack across months, and each grant expires 365 days after issue. Oldest-expiring credits are used first. They cover eligible website rental and delivery charges, not membership fees, security payments, card holds or Film Fund entry. Credits are personal, non-transferable and cannot be withdrawn as cash. Cancellation does not remove already earned, unexpired credits."],
  ["Rental security", "For future bookings after your first combined rental/membership booking is confirmed, or after a separately purchased paid membership settles, while a paid membership is active and its paid billing period has not expired, the upfront refundable security payment is waived. A separate full card hold still applies and your bank may require authentication. Trials still require the upfront security payment. Verification, agreed rental terms and a valid card hold are required before handover. No card hold or future saved-card payment is guaranteed by an issuer."],
  ["Basket membership offers", "Basket recommendations start at £100 for Starter, £200 for Pro and £300 for Studio, based on rental and delivery charges after existing discounts, before VAT and before credit payments. Membership fees, refundable security payments and card holds do not count towards these thresholds. A qualifying paid membership added in the rental checkout receives a one-time rental discount per customer: £5 for Starter or £10 for Pro or Studio, in addition to first-month credit. A customer can claim only one joining discount across all plans. It cannot stack with the member weekend deal; it is not available during the free week and cannot be earned again by cancelling, refunding or rejoining. The savings shown include the first membership fee charged today, exclude refundable security and holds, and count only credit actually spent in that checkout. Unused future credit is shown separately, not counted as savings."],
  ["Weekend deals", "Pro and Studio offer two inclusive rental days for the ordinary price of one, or three for the ordinary price of two, for eligible Friday-to-Sunday dates. Two-day rentals must be Friday–Saturday or Saturday–Sunday; three-day rentals Friday–Sunday. The total reduction is capped at £100 across the entire rental. The deal is calculated from our ordinary duration rates, never increases the ordinary price, and cannot combine with coupons, contextual item offers or quiet-item discounts. Delivery benefits still apply, and store credit is a payment method rather than another discount. The confirmed checkout quote is the agreed charge."],
  ["Delivery", "Starter reduces the current eligible website delivery quote by 10%; Pro by 30%. Studio includes one eligible London delivery service per London calendar month, within our published delivery range. This covers the quoted round-trip delivery and collection service, not unlimited journeys or an address outside London. A pending checkout reserves the allowance; cancellation before delivery releases it. Once delivery is performed the allowance is consumed. Unused deliveries do not roll over. Further Studio deliveries are charged at the ordinary quoted rate."],
  ["Encore returning-renter tier", "An authenticated customer unlocks Encore after three completed and returned website rentals, each with a distinct checkout payment and rental date window. Multiple items, item additions, split bookings in one checkout, repeated date windows, pending rentals and cancelled bookings do not count as separate qualifying rentals. Encore automatically reduces eligible future rental charges by 10% after any ordinary item offers or permitted rental coupons. It does not reduce delivery charges, membership fees, security payments, card holds, damage or late fees, taxes or Film Fund entry. It does not stack with subscription benefits or a membership added at checkout; subscription terms take priority. The unlocked tier stays on the account. Verification and normal rental security rules still apply."],
  ["Changes and cancellation", "You can manage or cancel renewal through Membership settings in your account. Cancel before the next renewal to avoid that charge; benefits continue for the paid period, subject to a valid membership and rental safeguards. Cancel during your free week to avoid the first monthly charge. Switching plans must use the existing billing account and must not create a second subscription. Rentals already agreed retain their confirmed quote. We will disclose material changes before they take effect."],
  ["Consumer rights", "For a new online membership you may have a statutory 14-day cancellation right. Contact DB Cinema Rentals through your account conversation to exercise it. Where you explicitly request immediate services, any lawful proportionate charge for services actually supplied will be explained; nothing in these terms removes your statutory rights. Unused promotional credits associated with a refunded or reversed membership payment may be removed. If refunded membership credit has already been spent, that credit balance may be offset against future earned membership credit; it is not an automatic card charge. We will not automatically charge your card merely because earned credit has already been spent."],
  ["Film Fund", "Pro and Studio include the application fee for one qualifying project entry, subject to the separate Film Fund rules and eligibility at submission. Starter entries cost £15 and nonmember entries cost £30, once per project, with no multiple ticket purchases. An included entry is not automatic submission of a project, a guaranteed award, or a lottery entry. The fund is Coming soon: no applications or entry payments are accepted until an announced round opens."],
 ];
 return <><SiteHeader/><main className="mx-auto max-w-3xl px-6 py-14"><Link href="/membership" className="text-sm text-accent-300">← Membership</Link><h1 className="mt-6 font-display text-4xl text-white">Membership terms</h1><p className="mt-3 text-xs text-white/40">{MEMBERSHIP_TERMS_VERSION} · effective on acceptance</p><div className="mt-10 space-y-8">{sections.map(([title,text])=><section key={title}><h2 className="text-lg font-medium text-white">{title}</h2><p className="mt-2 text-sm leading-7 text-white/60">{text}</p></section>)}</div></main></>;
}
