"use client";
import {useEffect,useState} from "react";
import {useQuery} from "convex/react";
import {api} from "@cvx/_generated/api";
import {SmartImage} from "@/components/SmartImage";
import {rentalTitle} from "@/lib/rentalPresentation";
import styles from "./AdminInsights.module.css";

function Trend({series,field}:{series:{visitors:number;adds:number}[];field:"visitors"|"adds"}){
 const max=Math.max(1,...series.map(row=>row[field]));
 return <svg viewBox="0 0 120 34" aria-hidden="true"><polyline fill="none" stroke="currentColor" strokeWidth="1.5" points={series.map((row,i)=>`${i*120/Math.max(1,series.length-1)},${32-row[field]*30/max}`).join(" ")}/></svg>;
}
export function AdminInsights({token,onInventory}:{token:string;onInventory:()=>void}){
 const [days,setDays]=useState(30),[now,setNow]=useState(()=>Date.now()),[allEquipment,setAllEquipment]=useState(false),[allSearches,setAllSearches]=useState(false);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer)},[]);
 const data=useQuery(api.analytics.insights,{token,days,now});
 if(!data)return <p className={styles.state} aria-busy="true">Loading website insights…</p>;
 if(!data.authorized)return <p className={styles.state} role="alert">Unlock the admin panel to view insights.</p>;
 const maxAdds=Math.max(1,...data.top.map(row=>row.adds)),maxChart=Math.max(1,...data.series.flatMap(row=>[row.visitors,row.adds]));
 const exportReport=()=>{
   const rows=[['Section','Name','Count','Units'],['Summary','Unique browser sessions',data.uniqueVisitors,''],['Summary','Cart additions',data.cartAdds,''],['Summary','Connected Gaffer calls',data.gaffer,''],['Summary','Active memberships',data.membership.active,''],...data.top.map(row=>['Cart additions',row.title,row.adds,row.units]),...data.searches.map(([name,count])=>['Searches',name,count,'']),...data.misses.map(([name,count])=>['No-result searches',name,count,'']),...data.pages.map(([name,count])=>['Page visitors',name,count,'']),...data.series.map(row=>['Daily visitors',row.date,row.visitors,'']),...data.series.map(row=>['Daily cart additions',row.date,row.adds,''])];
   // Quote every field and neutralise spreadsheet formulas in customer search text.
   const csv=rows.map(row=>row.map(cell=>'"'+String(cell).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"').join(',')).join('\r\n');
   const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`db-cinema-insights-${days}days.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 };
 const rankings=(rows:[string,number][],empty:string)=>{const max=Math.max(1,...rows.map(row=>row[1]));return rows.length?<ol className={styles.rankings}>{rows.map(([name,count],i)=><li key={name}><span>{i+1}</span><strong title={name}>{name}</strong><i><b style={{width:`${count*100/max}%`}}/></i><em>{count}</em></li>)}</ol>:<p className={styles.empty}>{empty}</p>};
 return <section className={styles.insights} aria-label="Website insights">
  <header className={styles.heading}><div><h1>Insights &amp; Demand</h1><p>Understand what customers want and where bookings begin.</p></div><div className={styles.actions}><label><span className={styles.sr}>Reporting period</span><select value={days} onChange={event=>setDays(Number(event.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></label><button onClick={exportReport}>↓ &nbsp; Export report</button></div></header>
  <p className={styles.scope}>First-party activity · unique visitors are browser sessions · daily chart in UTC</p>
  <div className={styles.metrics}>{[{label:"Unique visitors",value:data.uniqueVisitors,note:"Distinct browser sessions",trend:"visitors"},{label:"Cart additions",value:data.cartAdds,note:"Includes marketing-only equipment",trend:"adds"},{label:"Active members",value:data.membership.active,note:"Current account entitlements"},{label:"Gaffer conversations",value:data.gaffer,note:"Connected website voice calls"},{label:"No-result searches",value:data.noResults,note:"Recorded unmet equipment searches"}].map(metric=><div key={metric.label}><span>{metric.label}</span><strong>{metric.value.toLocaleString("en-GB")}</strong><small>{metric.note}</small>{metric.trend&&<Trend series={data.series} field={metric.trend as "adds"|"visitors"}/>}</div>)}</div>
  <div className={styles.central}><section className={`${styles.panel} ${styles.equipment}`}><header><h2>Most added to cart</h2><span>Adds <b>Units</b></span></header><div className={styles.equipmentRows}>{(allEquipment?data.top:data.top.slice(0,5)).map(row=><article key={row.listingId??row.title}><SmartImage className={styles.equipmentPhoto} src={row.heroImage} fallbackSources={row.imageSources} alt={row.title}/><div><h3 title={row.title}>{rentalTitle(row.title)}</h3><small data-marketing={row.marketingOnly===true}><i/>{row.marketingOnly===true?"Marketing only":row.marketingOnly===false?"Rental listing":"Listing status unknown"}</small></div><div className={styles.bar}><i style={{width:`${row.adds*100/maxAdds}%`}}/></div><strong>{row.adds}</strong><span>{row.units}</span></article>)}</div>{!data.top.length&&<p className={styles.empty}>No cart additions recorded in this period.</p>}<button className={styles.link} onClick={()=>setAllEquipment(value=>!value)}>{allEquipment?"Show fewer items":"View all recorded equipment"} &nbsp; →</button></section>
   <div className={styles.right}><section className={`${styles.panel} ${styles.chart}`}><header><h2>Visitors &amp; cart activity</h2><div className={styles.legend}><span><i/>Unique visitors</span><span><i/>Cart additions</span></div></header><svg viewBox="0 0 560 180" role="img" aria-label="Daily unique browser sessions and cart additions"><title>Daily activity over the last {days} days</title>{[0,1,2,3].map(i=><g key={i}><line x1="30" x2="550" y1={20+i*45} y2={20+i*45} stroke="#ffffff12"/><text x="1" y={24+i*45} fill="#b2b0a8" fontSize="10">{Math.round(maxChart*(3-i)/3)}</text></g>)}{["visitors","adds"].map((field,index)=><polyline key={field} fill="none" stroke={index?"#c99978":"#8fcea0"} strokeWidth="2" points={data.series.map((row,i)=>`${30+i*520/Math.max(1,days-1)},${155-row[field as "visitors"|"adds"]*135/maxChart}`).join(" ")}/> )}</svg><div className={styles.chartDates}>{data.series.filter((_,i)=>i===0||i===Math.floor(days/2)||i===days-1).map(row=><span key={row.date}>{new Intl.DateTimeFormat("en-GB",{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(row.date))}</span>)}</div></section>
   <section className={`${styles.panel} ${styles.memberships}`}><h2>Memberships</h2><div className={styles.memberGrid}><div className={styles.memberNumbers}><div><strong>{data.membership.active}</strong><span>Active<br/>members</span></div><div><strong>{data.membership.new}</strong><span>New in<br/>period</span></div><div><strong>{data.membership.scheduledCancellations}</strong><span>Scheduled<br/>cancellations</span></div></div><div className={styles.tiers}>{data.membership.tiers.map(([tier,count])=><div key={tier}><span>{tier}</span><i><b style={{width:`${count*100/Math.max(1,data.membership.active)}%`}}/></i><strong>{count}</strong></div>)}{!data.membership.tiers.length&&<p className={styles.empty}>No active memberships.</p>}</div></div></section></div>
  </div>
  <div className={styles.bottom}><section className={styles.panel}><h2>Popular searches &amp; tags</h2>{rankings(allSearches?data.searches:data.searches.slice(0,5),"No search terms recorded yet.")}<button className={styles.link} onClick={()=>setAllSearches(value=>!value)}>{allSearches?"Show fewer searches":"View recorded searches"} →</button></section><section className={styles.panel}><h2>Unmet demand</h2><p className={styles.subtitle}>Searches that returned no results</p>{rankings(data.misses.slice(0,5),"No unsuccessful searches recorded.")}<button className={styles.link} onClick={onInventory}>Review inventory &amp; demand →</button></section><section className={styles.panel}><h2>Gaffer &amp; website activity</h2><div className={styles.activity}>{[["Connected Gaffer calls",data.gaffer],["Website checkout starts",data.checkouts],["Interest registrations",data.interest]].map(([label,count])=><div key={label}><strong>{count}</strong><div><span>{label}</span><i><b style={{width:`${Number(count)*100/Math.max(1,data.gaffer,data.checkouts,data.interest)}%`}}/></i></div></div>)}</div><p className={styles.subtitle}>Checkout and interest totals cover the website; they are not attributed to Gaffer.</p></section></div>
  <section className={`${styles.panel} ${styles.pages}`}><h2>Most visited pages</h2>{rankings(data.pages,"No identifiable page sessions recorded.")}</section>
 </section>;
}
