"use client";
import { useState } from "react";
import { useQuery,useMutation } from "convex/react";
import { api } from "@cvx/_generated/api";
export function FilmFundAdmin({token}:{token:string}){const info=useQuery(api.filmFund.adminOverview,{token}),setRound=useMutation(api.filmFund.setRound),[message,setMessage]=useState(""),[selected,setSelected]=useState<string>();if(!info)return null;return <section className="rounded-3xl border border-white/10 bg-white/[.02] p-6"><p className="text-[10px] uppercase tracking-[.2em] text-white/40">DB Cinema Film Fund · coming soon</p><div className="mt-4 flex flex-wrap items-baseline gap-3"><span className="font-poster text-5xl text-accent-200">{info.signupCount}</span><h2 className="text-lg text-white">launch notification signups</h2></div><p className="mt-3 text-sm text-white/50">Applications and ticket purchases stay closed. Dates below are proposed and can be revised before opening.</p><div className="mt-6 grid gap-5 md:grid-cols-2">{info.rounds.map(r=><form key={r.slug} className="rounded-2xl border border-white/10 p-4" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await setRound({token,slug:r.slug,opensAt:Date.parse(String(f.get('opensAt'))),deadline:Date.parse(String(f.get('deadline'))),announcementAt:Date.parse(String(f.get('announcementAt')))});setMessage('Dates saved. The round is still Coming soon.');}catch(e:any){setMessage(e.message);}}}><h3 className="text-white">{r.name}</h3>{([['opensAt','Opening'],['deadline','Deadline'],['announcementAt','Winner announcement']] as const).map(([field,label])=><label key={field} className="mt-3 block text-xs text-white/50">{label} · UTC<input name={field} type="datetime-local" defaultValue={new Date(r[field]).toISOString().slice(0,16)} className="input mt-1 w-full"/></label>)}<button className="btn-ghost mt-4 px-4 py-2 text-xs">Save proposed dates</button></form>)}</div><p role="status" className="mt-4 text-xs text-accent-200">{message}</p><h3 className="mt-8 text-lg text-white">Submitted projects · {info.projects.length}</h3>{!info.projects.length&&<p className="mt-2 text-sm text-white/40">No submitted applications. Private drafts are excluded.</p>}{info.projects.map(p=><div key={p._id} className="mt-3 rounded-xl border border-white/10 p-4"><h4 className="text-white">{p.title}</h4><p className="mt-1 text-xs text-white/50">{p.roundSlug} · {p.reviewStatus} · {p.entryIncluded?'Included membership entry':'Single project entry'}</p><p className="mt-2 text-sm text-white/50">{p.synopsis}</p><button onClick={()=>setSelected(selected===p._id?undefined:p._id)} className="mt-3 text-xs text-accent-300">{selected===p._id?"Close review":"Open application and files →"}</button>{selected===p._id&&<ApplicationReview token={token} projectId={p._id}/>}</div>)}</section>;}

function ApplicationReview({token,projectId}:{token:string;projectId:string}){
 const data=useQuery(api.filmFund.adminApplication,{token,projectId:projectId as any}),review=useMutation(api.filmFund.reviewApplication),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 if(!data)return <p className="mt-4 text-xs text-white/40">Loading private application…</p>;
 return <div className="mt-5 space-y-5 border-t border-white/10 pt-5">
 <p className="text-xs text-white/50">Applicant: {data.applicantEmail} · {data.project.tags.join(" · ")}</p>
 <div><h5 className="text-sm text-white">Creative letter</h5><p className="mt-2 whitespace-pre-wrap text-sm text-white/60">{data.project.letter}</p></div>
 <div><h5 className="text-sm text-white">Crew</h5>{data.project.crew.map((c,i)=><div key={i} className="mt-3 rounded-xl bg-white/[.03] p-3"><a href={c.profile} target="_blank" rel="noopener noreferrer" className="text-sm text-accent-200">{c.name} · {c.role} ↗</a><p className="mt-1 text-xs text-white/50">{c.bio}</p></div>)}</div>
 <div className="flex flex-wrap gap-2">{data.files.map(f=><a key={f.id} href={f.url??undefined} target="_blank" rel="noopener noreferrer" className="rounded-lg border border-white/10 px-3 py-2 text-xs text-accent-200">{f.kind}: {f.name}{f.durationSeconds?` · ${Math.round(f.durationSeconds)}s`:""} ↗</a>)}</div>
 <form onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setMessage("");try{await review({token,projectId:projectId as any,status:String(form.get('status')) as any,note:String(form.get('note'))});setMessage('Review saved. No applicant notification has been sent.');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}} className="space-y-3">
 <label className="block text-xs text-white/50">Decision<select name="status" defaultValue={data.project.reviewStatus??"new"} className="input mt-1 w-full">{[['new','New'],['shortlisted','Shortlisted'],['winner','Winner · 7 days of gear'],['runner_up','Runner-up · 2 days of gear'],['not_selected','Not selected']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
 <label className="block text-xs text-white/50">Private review note<textarea name="note" defaultValue={data.project.reviewNote??""} maxLength={4000} rows={3} className="input mt-1 w-full"/></label>
 <button disabled={busy} className="btn-ghost px-4 py-2 text-xs">{busy?'Saving…':'Save review'}</button><p role="status" className="text-xs text-accent-200">{message}</p>
 </form></div>;
}
