"use client";
import {useEffect,useId,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {useQuery,useMutation,useAction} from "convex/react";
import {api} from "@cvx/_generated/api";
import {SmartImage} from "@/components/SmartImage";
import {formatGbp} from "@/lib/pricing";
import {rentalTitle} from "@/lib/rentalPresentation";
import drawer from "@/components/rentals/RentalRequestApply.module.css";
import swapStyles from "./RentalKitSwap.module.css";
import styles from "@/components/rentals/RentalAdditionApproval.module.css";
const date=(at:number)=>new Date(at).toLocaleDateString("en-GB",{timeZone:"UTC",day:"numeric",month:"short",year:"numeric"});
export function RentalKitSwap({token,bookingId,id,onClose,returnFocus,admin=true}:{token:string;bookingId:string;id:string;onClose:()=>void;returnFocus?:HTMLElement|null;admin?:boolean}){return <Swap key={JSON.stringify([token,bookingId,id,admin])} token={token} bookingId={bookingId} id={id} onClose={onClose} returnFocus={returnFocus} admin={admin}/>;}
function Swap({token,bookingId,id,onClose,returnFocus,admin=true}:{token:string;bookingId:string;id:string;onClose:()=>void;returnFocus?:HTMLElement|null;admin?:boolean}){
 const dialog=useRef<HTMLDialogElement>(null),title=useId(),[refreshKey,setRefreshKey]=useState(0);
 const args={token,bookingId:bookingId as any,id:id as any},alive=useRef(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[consent,setConsent]=useState(false);
 const live=useQuery(api.rentalSwaps.preview,admin?{...args,refreshKey}:"skip"),saved=useQuery(api.rentalSwaps.proposal,{...args,admin,refreshKey});
 const q=saved?{...saved,available:true as const}:admin?live:undefined;
 const offer=useMutation(api.rentalSwaps.offer),respond=useMutation(api.rentalSwaps.respond),withdraw=useMutation(api.rentalSwaps.withdrawOffer),apply=useMutation(api.rentalSwaps.applyAgreedSwap),startPayment=useAction(api.rentalAdditions.startPaidSwap);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function act(kind:"offer"|"accepted"|"declined"|"withdraw"|"apply"|"payment"){
  if(busy||!q?.available)return;
  setBusy(true);setError("");
  try{if(kind==="offer")await offer({...args,quoteKey:q.quoteKey});else if(kind==="payment")await startPayment({...args,quoteKey:q.quoteKey});else if(kind==="apply")await apply({...args,quoteKey:q.quoteKey});else if(kind==="withdraw")await withdraw(args);else await respond({...args,quoteKey:q.quoteKey,decision:kind});}
  catch(e){if(alive.current)setError(e instanceof Error?e.message:"Please retry the saved proposal.");}
  finally{if(alive.current)setBusy(false);}
 }
 useEffect(()=>{const node=dialog.current,previous=returnFocus??document.activeElement as HTMLElement|null;if(node&&!node.open)node.showModal();return()=>{if(node?.open)node.close();if(previous?.isConnected)previous.focus();};},[]);
 useEffect(()=>{const timer=setInterval(()=>setRefreshKey(n=>n+1),60000);return()=>clearInterval(timer);},[]);
 return createPortal(<dialog ref={dialog} className={drawer.dialog} aria-labelledby={title} onCancel={event=>{event.preventDefault();if(!busy)onClose();}}><div className={`${drawer.panel} ${swapStyles.panel}`} data-testid="admin-kit-swap"><header className={drawer.header}><div><span className={drawer.brand}>DB <span>CINEMA</span><small>RENTALS</small></span><h2 id={title}>{admin?"Review agreed swap":"Your swap proposal"}</h2></div><button type="button" className={drawer.close} aria-label="Close swap review" disabled={busy} onClick={onClose}>×</button></header>
 {saved===undefined||admin&&live===undefined&&!saved?<p role="status">Checking the agreed kit and price difference…</p>:!q?.available?<p role="alert" className={drawer.error}>{q?.reason??"This swap is unavailable."}</p>:<>
 <section className={`${styles.comparison} ${swapStyles.comparison}`} aria-label="Agreed equipment swap"><div className={styles.kit}><h3>Original equipment</h3><SmartImage src={q.source.heroImage} fallbackSources={q.source.imageSources} alt={q.source.title} className={styles.photo}/><strong>{q.source.qty}× {rentalTitle(q.source.title)}</strong></div><span className={styles.arrow} aria-hidden="true">→</span><div className={`${styles.kit} ${styles.proposed}`}><h3>Replacement</h3><SmartImage src={q.replacement.heroImage} fallbackSources={q.replacement.imageSources} alt={q.replacement.title} className={styles.photo}/><strong>{q.replacement.qty}× {rentalTitle(q.replacement.title)}</strong></div></section>
 <section className={drawer.section}><h3>Agreed rental period</h3><p>{date(q.start)} – {date(q.end)}</p><p className={drawer.note}>Collection {q.pickupTime??"to confirm"} · Return {q.returnTime??"to confirm"} · London</p></section>
 <section className={styles.quote} data-testid="swap-price-difference"><h3>Price difference</h3><dl><div><dt>Original equipment rental</dt><dd>{formatGbp(q.originalAmount)}</dd></div><div><dt>Replacement equipment rental</dt><dd>{formatGbp(q.replacementAmount)}</dd></div><div><dt>Rental difference</dt><dd>{q.difference<0?"−":"+"}{formatGbp(Math.abs(q.difference))}</dd></div>{q.securityCharge>0&&<div><dt>Additional refundable security</dt><dd>{formatGbp(q.securityCharge)}</dd></div>}</dl>{q.charge>0&&<div className={styles.total} data-testid="swap-additional-payment"><span>Additional payment</span><strong>{formatGbp(q.charge)}</strong></div>}{q.refund>0&&<div className={styles.total} data-testid="swap-original-method-refund"><span>Proposed refund to original payment method</span><strong>{formatGbp(q.refund)}</strong></div>}{q.charge===0&&q.refund===0&&<div className={styles.total}><span>No additional cash payment</span><strong>{formatGbp(0)}</strong></div>}{q.nonCashDifference>0&&<p className={drawer.note}>{formatGbp(q.nonCashDifference)} exceeds the remaining refundable rental payment. Redeemed credits and amounts already refunded are separate from a new cash refund.</p>}<div className={styles.security}><span aria-hidden="true">◇</span><div><strong>Replacement card authorisation · {formatGbp(q.holdTotal)}</strong><p>A card authorisation is separate from a payment or cash refund.</p></div></div></section>
 {saved&&<section className={drawer.section} data-testid="swap-proposal-status"><h3>{saved.state==="applied"?"Kit updated":saved.state==="accepted"?"Accepted · awaiting settlement":saved.state==="declined"?"Proposal declined":saved.state==="withdrawn"?"Proposal withdrawn":admin?"Awaiting renter decision":"Awaiting your decision"}</h3><p className={drawer.note}>{saved.state==="applied"?"The agreed replacement is booked. The payment and security amounts shown above are recorded with your rental.":saved.state==="accepted"?"Your acceptance is saved. The original rental remains unchanged until payment/refund, security and the kit update are confirmed.":saved.state==="offered"?"Review the exact saved kit and amounts above. Accepting records your agreement; it does not complete a payment or kit change.":"The original rental and payments remain unchanged."}</p>{saved.reason&&<p role="alert" className={drawer.error}>{saved.reason}</p>}</section>}
 {!admin&&saved?.state==="offered"&&saved.current&&<label className={drawer.note}><input type="checkbox" checked={consent} disabled={busy} onChange={event=>setConsent(event.target.checked)}/> I agree to this kit, price difference and refundable security under the <a href="/legal/terms" target="_blank" rel="noopener noreferrer">rental terms</a>.</label>}
 <p className={drawer.note}>{saved?"These are the saved proposal amounts.":"This is a live calculation."} {saved?.state==="applied"?" The agreed replacement is now part of your rental.":" The original kit, payment and authorisation remain unchanged."}{q.activeRental?" The collected equipment also needs its return and handover recorded before stock can be released.":""}</p>
 </>}{error&&<p role="alert" className={drawer.error}>{error}</p>}<footer className={`${drawer.actions} ${swapStyles.actions}`}>
 {admin&&!saved&&q?.available&&<button type="button" disabled={busy} data-primary="true" className={drawer.primary} onClick={()=>void act("offer")}>{busy?"Saving proposal…":"Send proposal for review"}</button>}
 {admin&&saved?.state==="accepted"&&"canApply" in saved&&saved.canApply&&<button type="button" disabled={busy} data-primary="true" className={drawer.primary} onClick={()=>void act("apply")}>{busy?"Updating booked kit…":"Apply agreed swap"}</button>}
 {admin&&saved?.state==="accepted"&&"canStartPayment" in saved&&(saved.canStartPayment||saved.settlement?.status==="prepared")&&<button type="button" disabled={busy} data-primary="true" className={drawer.primary} onClick={()=>void act("payment")}>{busy?"Preparing payment…":"Prepare difference payment"}</button>}
 {saved?.settlement?.paymentUrl&&<a className={drawer.primary} data-primary="true" href={saved.settlement.paymentUrl} target="_blank" rel="noopener noreferrer">{admin?"Open saved payment link":"Pay agreed difference"}</a>}
 {saved?.settlement&&["paid","requires_action","held","withdrawing","refund_pending","refund_failed"].includes(saved.settlement.status)&&<p role="status" className={drawer.note}>Settlement · {saved.settlement.status.replaceAll("_"," ")}. Check the linked rental controls for payment, bank approval or withdrawal recovery.</p>}
 {admin&&saved&&!saved.settlement&&["offered","accepted"].includes(saved.state)&&<button type="button" disabled={busy} onClick={()=>void act("withdraw")}>{busy?"Saving…":"Withdraw proposal"}</button>}
 {!admin&&saved?.state==="offered"&&<><button type="button" disabled={busy||!consent||!saved.current} data-primary="true" className={drawer.primary} onClick={()=>void act("accepted")}>{busy?"Saving…":"Accept proposal"}</button><button type="button" disabled={busy} onClick={()=>void act("declined")}>Decline proposal</button></>}
 <button type="button" disabled={busy} onClick={onClose}>Back to rental requests</button></footer></div></dialog>,document.body);
}
