"use client";
import {useState} from "react";
import {useAction} from "convex/react";
import {api} from "@cvx/_generated/api";
import {formatGbp} from "@/lib/pricing";
import styles from "./RentalRefundRecovery.module.css";
type Refund={cancelledBeforeBankAt?:number;_id:string;requestId:string;reason:string;status:string;amountPence:number;createdAt:number;providerCheckedAt?:number;bankReversalAt?:number;parts?:{paymentIntentId:string;stripeRefundId:string;status:string;amountPence:number;failureReason?:string}[]};
const money=(r:Refund,status:string)=>r.parts?r.parts.filter(p=>p.status===status).reduce((n,p)=>n+p.amountPence,0):r.status===status?r.amountPence:0;
const london=(at:number)=>new Date(at).toLocaleString("en-GB",{timeZone:"Europe/London",day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"});
export function RentalRefundRecovery({token,bookingId,refunds,onResume,busy=false}:{token:string;bookingId:string;refunds:Refund[];onResume:(refund:Refund)=>Promise<void>;busy?:boolean}){
 const refresh=useAction(api.checkout.refreshRentalRefund),[checking,setChecking]=useState<string|null>(null),[error,setError]=useState(""),[result,setResult]=useState("");
 async function check(r:Refund){if(checking||busy)return;setChecking(r._id);setError("");setResult("");try{const data=await refresh({token,bookingId:bookingId as any,id:r._id as any});setResult(data.stale?"This check was superseded. Check again for a fresh bank status.":`${formatGbp(data.confirmed)} confirmed · ${formatGbp(data.processing)} processing · ${formatGbp(data.outstanding)} outstanding.`);}catch(e){setError(e instanceof Error?e.message:"The bank status could not be checked.");}finally{setChecking(null);}}
 if(!refunds.length)return null;
 return <section className={styles.panel} aria-label="Original payment refunds" data-testid="owner-refund-recovery"><header className={styles.header}><div><span className={styles.eyebrow}>Rental settlement</span><h3>Refunds to original payments</h3></div><span className={styles.count}>{refunds.length} {refunds.length===1?"request":"requests"}</span></header>
 <div className={styles.list}>{[...refunds].sort((a,b)=>b.createdAt-a.createdAt).map(r=>{const confirmed=money(r,"succeeded"),pending=money(r,"pending"),outstanding=r.cancelledBeforeBankAt?0:Math.max(0,r.amountPence-confirmed-pending),label=r.cancelledBeforeBankAt?"Withdrawn before bank request":({prepared:"Ready to issue",pending:"Bank processing",succeeded:"Refund confirmed",failed:"Needs attention"} as Record<string,string>)[r.status]??"Team review";return <article className={styles.refund} key={r._id} data-refund-id={r._id}><div className={styles.row}><div><h4>{formatGbp(r.amountPence/100)}</h4><time dateTime={new Date(r.createdAt).toISOString()}>{london(r.createdAt)} · London</time></div><span className={styles.badge} data-state={r.status}>{label}</span></div><p className={styles.reason}>{r.reason}</p>
 <div className={styles.metrics}><div><span>Confirmed</span><strong>{formatGbp(confirmed/100)}</strong></div><div><span>Processing</span><strong>{formatGbp(pending/100)}</strong></div><div><span>Outstanding</span><strong>{formatGbp(outstanding/100)}</strong></div></div><div className={styles.track} role="progressbar" aria-label="Refund confirmed" aria-valuemin={0} aria-valuemax={100} aria-valuenow={r.amountPence?Math.round(confirmed/r.amountPence*100):0}><span style={{width:`${r.amountPence?Math.min(100,confirmed/r.amountPence*100):0}%`}}/></div>
 {!!r.parts?.length&&<details className={styles.breakdown}><summary>Original payment breakdown</summary><dl>{r.parts.map((p,i)=><div key={p.paymentIntentId}><dt>Original payment {i+1}<small>{p.status==="succeeded"?"Confirmed":p.status==="pending"?"Processing with the bank":"Not completed"}{p.failureReason?` · ${p.failureReason.replaceAll("_"," ")}`:""}</small></dt><dd>{formatGbp(p.amountPence/100)}</dd></div>)}</dl></details>}
 {r.bankReversalAt&&r.status!=="succeeded"&&<p className={styles.attention}>The bank returned a previously confirmed refund. The outstanding amount needs a team repayment decision.</p>}{r.status==="failed"&&!r.bankReversalAt&&!r.cancelledBeforeBankAt&&<p className={styles.attention}>The outstanding amount needs a team decision. A bank-rejected refund may require another repayment method.</p>}
 {!r.cancelledBeforeBankAt&&<div className={styles.actions}><button type="button" disabled={busy||!!checking} onClick={()=>void check(r)}>{checking===r._id?"Checking bank…":"Check bank status"}</button>{["prepared","pending"].includes(r.status)&&<button type="button" disabled={busy||!!checking} onClick={()=>void onResume(r)}>Resume saved refund</button>}</div>}{r.cancelledBeforeBankAt&&<p className={styles.checked}>No original-payment refund was issued. The original rental remains in place.</p>}{r.providerCheckedAt&&<p className={styles.checked}>Bank status checked {london(r.providerCheckedAt)} · London</p>}</article>;})}</div>
 {error&&<p role="alert" className={styles.attention}>{error}</p>}{result&&<p role="status" className={styles.checked}>{result}</p>}</section>;
}
