import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { FILM_FUND_TERMS_VERSION } from "../../../../shared/filmFund";
export default function FilmFundTerms(){const sections=[
 ["Coming soon", "The DB Cinema Film Fund is operated by DB Cinema Rentals. Two judged rounds per year are planned. The fund currently accepts email notification signups and private draft preparation only: no application submissions or entry payments are open. Proposed dates are shown on the fund page; confirmed rules, deadlines, judging panel and available gear will be announced before each round opens."],
 ["One project, one entry", "The responsible applicant must be at least 18, hold a DB Cinema account and have authority from the project’s team and rights holders. Each project may have only one entry, with no purchases of multiple tickets to improve its chances. Pro and Studio include the application entry fee while eligible at submission; other entries cost £15 once per project. Payment or membership does not guarantee shortlisting or a prize. This is a judged creative competition, not a random draw or lottery."],
 ["Application requirements", "Submit the project title, synopsis and tags; a 250-word bio / creative letter; crew names, roles, biographies and HTTPS profile links; a PDF script; moodboard; supporting production document; and an MP4 pitch video of approximately one minute (55–65 seconds). Supporting files must be yours to share, within upload limits, and free of unlawful material. A complete, accepted submission must arrive before the published deadline. A saved draft alone is not an entry. Submitted applications are locked to preserve a fair review."],
 ["Judging", "Projects are assessed on artistic vision and originality, clarity of the pitch, feasibility and production planning, suitability of the requested gear and the crew’s readiness to complete the project. There is no random allocation. Conflicts of interest must be disclosed and judges with a material conflict will not assess the affected project. No preference is bought through extra payments. Applicants may request clarification of an administrative error; artistic decisions remain with the announced judging panel."],
 ["Equipment awards", "The selected project receives an agreed equipment package for up to seven consecutive rental days; the runner-up receives up to two. Awards are equipment use, not cash or ownership. Exact kit, dates and availability are agreed before handover. Delivery, insurance exclusions, damage, loss, late return and any required card hold remain subject to the agreed rental terms. Nothing promises unlimited gear, unavailable stock or an insurance claim’s acceptance. Awards cannot be resold or transferred to a different production without our written agreement."],
 ["Named producer credit", "An awarded production must include DB Cinema Rentals as a named producer in its film credits and agree the exact credit wording, placement, project timetable and permitted publicity in writing before equipment is supplied. The creative team keeps its film rights unless a separate written agreement expressly says otherwise. Entry alone grants no ownership of your script or film to DB Cinema. A limited permission to review submitted materials is required for judging; sharing clips or project information publicly requires the applicant’s separate agreement."],
 ["Payments, changes and consumer rights", "No charge is taken during Coming soon. Once a round opens, its checkout states the single £15 fee and the applicable cancellation and refund terms before payment. Duplicate charges and a canceled round will be refunded where due. We will not describe an application fee as increasing your chance of winning or let you pay twice for the same project. Your statutory consumer rights are preserved. Material changes, delays or cancellation of a round will be communicated to entrants."],
 ["Your information", "Project drafts and documents are private to your account and authorized DB Cinema reviewers. Do not include unnecessary identity documents, bank details or sensitive personal information in production uploads. Crew members must know their details are being submitted. Launch notification consent is separate from membership and from submitting a project, and can be withdrawn. Contact the team through your account to request correction or deletion, subject to records we must retain for payments and disputes."],
 ];return <><SiteHeader/><main className="mx-auto max-w-3xl px-6 py-14"><Link href="/film-fund" className="text-sm text-accent-300">← Film Fund</Link><h1 className="mt-6 font-display text-4xl text-white">Film Fund rules</h1><p className="mt-3 text-xs text-white/40">{FILM_FUND_TERMS_VERSION} · coming soon</p><div className="mt-10 space-y-8">{sections.map(([title,text])=><section key={title}><h2 className="text-lg text-white">{title}</h2><p className="mt-2 text-sm leading-7 text-white/60">{text}</p></section>)}</div></main></>;}
