"use client";
import Link from "next/link";
import { useQuery } from "convex/react";
import { api } from "@cvx/_generated/api";
import { SiteHeader } from "@/components/SiteHeader";
import { FilmFundInvite } from "@/components/FilmFundInvite";
import { FilmFundApplication } from "@/components/FilmFundApplication";
import { FilmFundHeart } from "@/components/FilmFundHeart";
const prizes=[{number:"7",title:"The selected project",label:"Days of gear",note:"Give your story room to breathe.",points:["An agreed cinema equipment package","Up to seven consecutive rental days","Kit and shoot dates planned with our team"]},{number:"2",title:"The runner-up",label:"Days of gear",note:"A little support can start something big.",points:["An agreed equipment package for your project","Up to two consecutive rental days","Support for a focused shoot or key scene"]}];
export default function FilmFundPage(){const schedule=useQuery(api.filmFund.schedule,{}),open=schedule?.rounds.some(r=>r.state==="open"&&r.opensAt<=Date.now()&&r.deadline>Date.now());return <><SiteHeader/><main className="fund-page mx-auto max-w-7xl px-5 pb-20 pt-8 sm:px-8 sm:pt-14">
 <FilmFundInvite compact/>
 <section className="fund-section fund-prizes" aria-labelledby="fund-prizes-title"><div className="fund-section-heading"><div><p className="fund-eyebrow">Your story. Our kit.</p><h2 id="fund-prizes-title" className="fund-section-title">Two projects.<br/><em>A real chance to create.</em></h2></div><p>Equipment, not a cash prize. Chosen for the idea, the people and the plan. No extra tickets. No buying better odds.</p></div>
 <div className="fund-prize-grid">{prizes.map((p,i)=><article className={`fund-prize-card ${i===0?"fund-prize-first":""}`} key={p.number}><div className="fund-prize-top"><span className="fund-eyebrow">{i===0?"First award":"Second award"}</span><FilmFundHeart className="fund-prize-heart"/></div><div className="fund-prize-number">{p.number}<span>{p.label}</span></div><h3>{p.title}</h3><p className="fund-prize-note">{p.note}</p><ul className="fund-check-list">{p.points.map(point=><li key={point}><span aria-hidden>↗</span>{point}</li>)}</ul></article>)}</div>
 <p className="fund-prize-fineprint">Awards are subject to agreed kit, availability and rental terms. Delivery, insurance exclusions and any required card hold still apply.</p></section>
 <section className="fund-section fund-why"><FilmFundHeart className="fund-why-heart"/><p className="fund-eyebrow">A little love for independent cinema</p><h2 className="fund-section-title">Great films start with<br/><em>people who care.</em></h2><p>We know how much of yourself goes into a passion project. The late nights. The favours. The crew who show up because they believe in it. This Fund is our way of showing up, too.</p><span className="fund-signature">With love, DB Cinema</span></section>
 <section className="fund-section" aria-labelledby="fund-dates-title"><div className="fund-section-heading"><div><p className="fund-eyebrow">Twice a year. A new beginning.</p><h2 id="fund-dates-title" className="fund-section-title">The next two chapters.</h2></div><p>{open?"Applications are open during the announced window.":"Proposed dates for our first rounds. We’ll confirm the opening by email; entries stay closed until then."}</p></div><div className="fund-dates-grid">{schedule?.rounds.map((r,i)=><article key={r.slug} className="fund-date-card"><div className="fund-date-top"><span className="fund-eyebrow">Round 0{i+1}</span><span className="fund-round-badge">{r.state.replace('_',' ')}</span></div><h3>{r.name}</h3><dl>{[["Applications open",r.opensAt],["Submission deadline",r.deadline],["Winner announcement",r.announcementAt]].map(([label,date])=><div key={label}><dt>{label}</dt><dd>{new Date(date).toLocaleDateString("en-GB",{timeZone:"Europe/London",day:"numeric",month:"long",year:"numeric"})}</dd></div>)}</dl></article>)}</div></section>
 <section id="application" className="fund-section fund-application-section"><div className="fund-section-heading"><div><p className="fund-eyebrow">The idea is only the beginning</p><h2 className="fund-section-title">Let’s meet <em>your film.</em></h2></div><p>You can prepare a private draft now. We’ll judge artistic vision, feasibility and your team’s readiness to make it happen.</p></div>
 <div className="fund-application-guide"><div><h3>Your pitch, in six parts.</h3><ul className="fund-check-list">{["Project synopsis and tags","A 250-word creative letter","Crew profiles, roles and biographies","Your script and moodboard","Supporting production documents","A one-minute pitch video"].map(t=><li key={t}><span aria-hidden>♡</span>{t}</li>)}</ul></div><div className="fund-entry-note"><p className="fund-eyebrow">One project. One entry.</p><h3>Included with Pro & Studio.</h3><p>Starter: <strong>£15 once per project.</strong> Nonmembers: <strong>£30 once per project.</strong> A membership or entry fee never guarantees selection. No payment is taken while the Fund is Coming soon.</p><p>Awarded films credit DB Cinema Rentals as a named producer and allow us to show the full finished film on our website to promote the Fund. You keep ownership.</p><Link href="/legal/film-fund" className="fund-rules-link">Read the full Fund rules ↗</Link></div></div><FilmFundApplication/></section>
 </main></>;}
