"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useAction, useMutation, useQuery } from "convex/react";
import { api } from "@cvx/_generated/api";
import { useAccount } from "./account/AccountProvider";
import { wordCount, FILM_FUND_TERMS_VERSION } from "../../shared/filmFund";
export function FilmFundApplication(){
 const{token}=useAccount(),projects=useQuery(api.filmFund.mine,token?{token}:"skip"),schedule=useQuery(api.filmFund.schedule,{});
 const save=useMutation(api.filmFund.saveDraft),url=useMutation(api.filmFund.uploadUrl),attach=useMutation(api.filmFund.attachDocument),video=useAction(api.filmFundMedia.verifyVideo),submit=useMutation(api.filmFund.submit),entryCheckout=useAction(api.filmFundPayments.start),finalizeEntry=useAction(api.filmFundPayments.finalize);
 const[id,setId]=useState<string>(),[title,setTitle]=useState(""),[synopsis,setSynopsis]=useState(""),[tags,setTags]=useState(""),[letter,setLetter]=useState(""),[crew,setCrew]=useState([{name:"",role:"Director",profile:"",bio:""}]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[terms,setTerms]=useState(false);
 const selected=projects?.find(p=>p._id===id),round=schedule?.rounds.find(r=>r.state==="open"&&Date.now()>=r.opensAt&&Date.now()<=r.deadline);
 const locked=selected?.state==="submitted";
 const finalizedEntry=useRef(false);
 useEffect(()=>{if(finalizedEntry.current)return;const sessionId=new URL(window.location.href).searchParams.get('entry_session');if(!sessionId)return;finalizedEntry.current=true;window.history.replaceState(null,'','/film-fund#application');void finalizeEntry({sessionId}).then(r=>setMessage(r.paid?'Your single project entry is paid. Open your saved project and submit the application.':'Payment has not completed. No entry has been submitted.')).catch(e=>setMessage(e.message));},[finalizeEntry]);
 async function persist(){if(!token)throw Error("Sign in to save your draft.");const result=await save({token,projectId:id as any,title,synopsis,tags:tags.split(",").map(s=>s.trim()).filter(Boolean),letter,crew});setId(result);return result;}
 async function upload(file:File,kind:"script"|"moodboard"|"document"|"video"){if(!token||busy)return;setBusy(true);setMessage("");try{const projectId=await persist();const uploadUrl=await url({token,projectId});const response=await fetch(uploadUrl,{method:"POST",headers:{"Content-Type":file.type},body:file});if(!response.ok)throw Error("Upload failed.");const{storageId}=await response.json();if(kind==="video")await video({token,projectId,storageId,name:file.name});else await attach({token,projectId,storageId,kind,name:file.name});setMessage(`${file.name} saved${kind==="video"?" and duration verified":""}.`);}catch(e:any){setMessage(e.message??"Upload failed.");}finally{setBusy(false);}}
 if(!token)return <div className="mt-6 rounded-2xl border border-white/10 bg-white/[.02] p-6"><p className="text-sm text-white/55">Keep your script, crew and pitch together in a private saved draft.</p><Link href="/account" className="mt-3 inline-block text-sm text-accent-300">Create an account or sign in →</Link></div>;
 return <div className="mt-6 rounded-3xl border border-white/10 bg-white/[.02] p-5 sm:p-8"><div className="flex flex-wrap justify-between gap-3"><h3 className="text-lg text-white">Your private application draft</h3><span className="rounded-full bg-white/5 px-3 py-1 text-[11px] text-white/40">{locked?"Submitted":"Drafts only · coming soon"}</span></div><div className="mt-4 flex flex-wrap gap-2">{projects?.map(p=><button key={p._id} onClick={()=>{setId(p._id);setTitle(p.title);setSynopsis(p.synopsis);setTags(p.tags.join(", "));setLetter(p.letter);setCrew(p.crew);setMessage("");}} className={`rounded-full border px-3 py-2 text-xs ${id===p._id?"border-accent-300/40 text-accent-200":"border-white/10 text-white/50"}`}>{p.title}</button>)}<button onClick={()=>{setId(undefined);setTitle("");setSynopsis("");setTags("");setLetter("");setCrew([{name:"",role:"Director",profile:"",bio:""}]);}} className="rounded-full border border-white/10 px-3 py-2 text-xs text-white/50">+ New project</button></div>
 <fieldset disabled={busy||locked} className="mt-6 space-y-5 disabled:opacity-60"><label className="block text-xs text-white/60">Project title<input value={title} readOnly={!!id} onChange={e=>setTitle(e.target.value)} maxLength={150} className="input mt-2 w-full"/></label><label className="block text-xs text-white/60">Synopsis<textarea value={synopsis} onChange={e=>setSynopsis(e.target.value)} maxLength={10000} rows={3} className="input mt-2 w-full"/></label><label className="block text-xs text-white/60">Tags · separate with commas<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="Short film, drama, London" className="input mt-2 w-full"/></label><label className="block text-xs text-white/60">Bio / creative letter · {wordCount(letter)} / 250 words<textarea value={letter} onChange={e=>setLetter(e.target.value)} rows={7} maxLength={10000} className="input mt-2 w-full"/></label>
 <div><h4 className="text-sm text-white">Crew and profiles</h4>{crew.map((c,i)=><div key={i} className="mt-3 grid gap-3 rounded-2xl border border-white/10 p-4 sm:grid-cols-2">{([['name','Full name'],['role','Role'],['profile','HTTPS profile URL'],['bio','Crew biography']] as const).map(([key,label])=><label key={key} className="text-xs text-white/50">{label}<input value={c[key]} onChange={e=>setCrew(rows=>rows.map((row,j)=>j===i?{...row,[key]:e.target.value}:row))} className="input mt-1 w-full"/></label>)}{crew.length>1&&<button onClick={()=>setCrew(rows=>rows.filter((_,j)=>j!==i))} className="text-left text-xs text-rose-300">Remove crew member</button>}</div>)}<button onClick={()=>setCrew(rows=>[...rows,{name:"",role:"",profile:"",bio:""}])} disabled={crew.length>=30} className="mt-3 text-xs text-accent-300">+ Add crew member</button></div>
 <div className="grid gap-3 sm:grid-cols-2">{(['script','moodboard','document','video'] as const).map(kind=><label key={kind} className="rounded-2xl border border-white/10 p-4 text-xs text-white/55"><span className="block font-medium capitalize text-white">{kind==='video'?'Pitch video · MP4, 55–65 seconds':kind==='document'?'Supporting production document':kind}</span><span className="mt-1 block text-[11px] text-white/35">{kind==='video'?'Up to 120 MB':kind==='script'?'PDF · up to 20 MB':'PDF or image · up to 20 MB'}{kind==='document'?` · ${selected?.documentIds.length??0} saved`:(selected?.[kind==='script'?'scriptId':kind==='moodboard'?'moodboardId':'videoId']?' · Saved':'')}</span><input type="file" accept={kind==='video'?'video/mp4':kind==='script'?'application/pdf':'application/pdf,image/jpeg,image/png,image/webp'} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,kind);e.target.value='';}} className="mt-3 block w-full min-w-0 text-[11px] file:mr-2 file:rounded-md file:border-0 file:bg-white/10 file:px-3 file:py-2 file:text-white/70"/></label>)}</div>
 <button onClick={async()=>{setBusy(true);setMessage('');try{await persist();setMessage('Draft saved. No submission or payment has been made.');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}} className="btn-ghost px-5 py-3 text-sm">Save draft</button>
 </fieldset>
 <p role="status" className="mt-4 text-xs text-accent-200">{busy?'Saving / verifying…':message}</p><label className="mt-5 flex gap-2 text-xs text-white/45"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>I accept the <Link href="/legal/film-fund" className="text-accent-300 underline">Film Fund rules</Link> and named producer credit requirement.</span></label><button disabled={!round||!terms||busy||locked} onClick={async()=>{if(!token||!round)return;setBusy(true);try{const projectId=await persist();if(!selected?.entryPaid){const entry=await entryCheckout({token,projectId,roundSlug:round.slug,termsVersion:FILM_FUND_TERMS_VERSION});if(entry.url){window.location.assign(entry.url);return;}}await submit({token,projectId,roundSlug:round.slug,termsVersion:FILM_FUND_TERMS_VERSION});setMessage('Application submitted.');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}} className="btn-primary mt-4 px-5 py-3 text-sm disabled:opacity-30">{round?(selected?.entryPaid?'Submit paid application':'Submit · included with Pro / Studio, otherwise £15 once'):'Submissions open soon'}</button><p className="mt-3 text-xs text-white/35">No entry payment is taken while the fund is Coming soon.</p></div>;
}
